/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
let GameConfig={}

GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

// GameConfig.host="https://www.marphy.cn/toone/web/"  //小程序跨域
GameConfig.host="" //h5调试

export default GameConfig;

